export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'